"""empty message

Revision ID: ad7c379c8a76
Revises:
Create Date: 2024-11-26 17:56:11.238822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad7c379c8a76"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariffs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cargo_type", sa.String(length=255), nullable=False),
        sa.Column("rate", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tariffs_cargo_type"),
        "tariffs",
        ["cargo_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tariffs_cargo_type"), table_name="tariffs")
    op.drop_table("tariffs")
    # ### end Alembic commands ###
